User can select comversion #1031
SecureAuthCorp/impacket pull request #1044
Opened 2021-03-23 10:02 UTC by zexusx26

Server want 5.6 DCOM version, but client version is 5.7.

```bash
$ python3 wmiquery.py user:pass@10.50.240.10 -debug
Impacket v0.9.23.dev1+20210315.121412.a16198c3 - Copyright 2020 SecureAuth Corporation

[+] Impacket Library Installation Path: /root/impacket/impacket
[+] Target system is 10.50.240.10 and isFDQN is False
[+] StringBinding: corp-6jl4yybmxr[1025]
[+] StringBinding: 10.50.240.10[1025]
[+] StringBinding chosen: ncacn_ip_tcp:10.50.240.10[1025]
[-] RPC_E_VERSION_MISMATCH - The version of OLE on the client and server machines does not match.
```

Now we cat define (globally) client DCOM version (e.g. 5.6).

```bash
$ python3 wmiquery.py user:pass@10.50.240.10 -debug -com-version 5.6 -debug
Impacket v0.9.23.dev1+20210315.121412.a16198c3 - Copyright 2020 SecureAuth Corporation

[+] Impacket Library Installation Path: /root/impacket/impacket
[+] Target system is 10.50.240.10 and isFDQN is False
[+] StringBinding: corp-6jl4yybmxr[1025]
[+] StringBinding: 10.50.240.10[1025]
[+] StringBinding chosen: ncacn_ip_tcp:10.50.240.10[1025]
[!] Press help for extra shell commands
WQL>
```

2021-04-21 16:09 UTC, 0xdeaddood requested changes
Hi @zexusx26! This is a great addition! 
I have a couple of points to review before merging:
- There are some typos to fix in the help section.
- Have you tested dcomexec.py against Windows versions prior to 2003? (Win XP or Win 2000) I think there are some issues executing the shell command with the objects ShellWindows and ShellBrowserWindow.

Thanks!

2021-04-26 03:17 UTC, zexusx26 commented
I have tested it with Win2000 Server (I don't know version) with patch #1045:
```
root@3172b3d10606:/app/impacket# wmiquery.py user:pass@10.51.244.19 -debug
Impacket v0.9.23.dev1+20210315.121412.a16198c3 - Copyright 2020 SecureAuth Corporation

[+] Impacket Library Installation Path: /app/impacket/impacket
[+] Target system is 10.51.244.19 and isFDQN is False
[+] StringBinding: \\\\ADMIN-D8831EAB5[\\pipe\\WMIEP_3d0]
[+] StringBinding: admin-d8831eab5[2205]
[+] StringBinding: 10.51.244.19[2205]
[+] StringBinding chosen: ncacn_ip_tcp:10.51.244.19[2205]
[-] RPC_E_VERSION_MISMATCH - The version of OLE on the client and server machines does not match.
```

```
root@3172b3d10606:/app/impacket# wmiquery.py user:pass@10.51.244.19 -debug -com-version 5.6
Impacket v0.9.23.dev1+20210315.121412.a16198c3 - Copyright 2020 SecureAuth Corporation

[+] Impacket Library Installation Path: /app/impacket/impacket
[+] Target system is 10.51.244.19 and isFDQN is False
[+] StringBinding: \\\\ADMIN-D8831EAB5[\\pipe\\WMIEP_3d0]
[+] StringBinding: admin-d8831eab5[2205]
[+] StringBinding: 10.51.244.19[2205]
[+] StringBinding chosen: ncacn_ip_tcp:10.51.244.19[2205]
[!] Press help for extra shell commands
WQL>
```

2021-04-27 20:39 UTC, 0xdeaddood approved these changes

2021-04-27 20:47 UTC, merged

2021-04-27 20:47 UTC, 0xdeaddood commented
Hi @zexusx26! 
I was asking you about **dcomexec.py** because I was having an error running it in old versions of Windows (not related to this PR). 

Thanks for the changes. Merging...