Get gpppasswords add single xml file parsing
SecureAuthCorp/impacket pull request #1086
Opened 2021-05-25 14:51 UTC by p0dalirius

## Added single XML file parsing on Get-GPPPassword

Added `-xmlfile` option to parse and extract Group Policy Preferences passwords from a specified XML file. This can be useful to parse GPP XML files offline, or obtained in another way.

```
# ./Get-GPPPassword.py LOCAL -xmlfile /tmp/Policy.xml -debug
Impacket v0.9.23.dev1+20210427.174742.fc72ebad - Copyright 2020 SecureAuth Corporation

[+] Impacket Library Installation Path: /usr/local/lib/python3.9/dist-packages/impacket
[+] Opening /tmp/Policy.xml XML file for reading ...
[*] NewName	: ADSAdmin
[*] Changed	: 2015-02-18 01:53:01
[*] Username	: 
[*] Password	: #Super@Secure&Password$2015?
[*] File	: /tmp/Policy.xml 
```

## References 
 - https://podalirius.net/en/articles/exploiting-windows-group-policy-preferences/
 - https://www.thehacker.recipes/active-directory-domain-services/movement/credentials/dumping/group-policies-preferences

2021-05-25 14:53 UTC, ShutdownRepo commented
FYI, we did just like secretsdump with the `target` positionnal and required argument being set to `LOCAL` when parsing local files.

2021-05-27 23:41 UTC, 0xdeaddood requested changes
Hi guys! This feature is great! I made some requests for changes to the PR before merging it.

2021-05-27 23:41 UTC, 0xdeaddood commented on examples/Get-GPPPassword.py
>      parser.add_argument('target', action='store', help='[[domain/]username[:password]@]<targetName or address>')
```suggestion
    parser.add_argument('target', action='store', help='[[domain/]username[:password]@]<targetName or address> or LOCAL'
                                                       ' (if you want to parse local files)')
```

2021-05-27 23:41 UTC, 0xdeaddood commented on examples/Get-GPPPassword.py
> +                logging.error(str(e))
```suggestion
    else:
        domain, username, password, address, lmhash, nthash = parse_target(args)
        try:
            smbClient= init_smb_session(args, domain, username, password, address, lmhash, nthash)
            g = GetGPPasswords(smbClient, args.share)
            g.list_shares()
            g.find_cpasswords(args.base_dir)
        except Exception as e:
            if logging.getLogger().level == logging.DEBUG:
                traceback.print_exc()
            logging.error(str(e))
```

2021-05-27 23:41 UTC, 0xdeaddood commented on examples/Get-GPPPassword.py
>      parser.add_argument('target', action='store', help='[[domain/]username[:password]@]<targetName or address>')
Like `secretsdump`, it would be nice to add the argument LOCAL to the help section.

2021-05-27 23:41 UTC, 0xdeaddood commented on examples/Get-GPPPassword.py
> +                logging.error(str(e))
There is an issue with the indentation. It doesn't work for remote extractions.

2021-05-28 19:25 UTC, 0xdeaddood approved these changes

2021-05-28 19:27 UTC, 0xdeaddood commented
Thanks @p0dalirius and @ShutdownRepo! Merging...

2021-05-28 19:27 UTC, merged