added 'mget' to smbclient.py
SecureAuthCorp/impacket pull request #1095
Opened 2021-06-09 20:27 UTC by deadjakk

This command allows for the downloading of multiple files, much like the 'mget' command of smbclient(1).

This a greatly desired function of smbclient.py and helps when dealing with download a large number of files from a directory. 
Very minimal changes were required to implement this, so it should be an easy addition.

The image below shows the result of the new 'mget' command.
![smbclient-mget](https://user-images.githubusercontent.com/30613497/121424632-2bca6200-c937-11eb-832c-c38ace69052d.png)

2021-06-09 21:42 UTC, 0xdeaddood commented
Hi @deadjakk! 
This is great! It was in my TO-DO list. I'll take a look.

2021-06-25 17:50 UTC, 0xdeaddood requested changes
Hi @deadjakk! It works great. I have a couple of comments: 

- I think we could check if the result of _do_ls_ (file_tuples) is a file to prevent downloading directories. 
- Could you change they year in the copyright header to 2021?

Thanks!

2021-06-25 17:50 UTC, 0xdeaddood commented on impacket/examples/smbclient.py
> +            fh.close()
```suggestion
            if file_tuple[1] == 0:
                filename = file_tuple[0]
                filename = filename.replace('/', '\\')
                fh = open(ntpath.basename(filename), 'wb')
                pathname = ntpath.join(self.pwd, filename)
                try:
                    LOG.info("Downloading %s" % (filename))
                    self.smb.getFile(self.share, pathname, fh.write)
                except:
                    fh.close()
                    os.remove(filename)
                    raise
                fh.close()
```

2021-06-25 17:50 UTC, 0xdeaddood commented on impacket/examples/smbclient.py
> +            fh.close()
We could add a file checker to avoid directory downloads.

2021-06-26 17:25 UTC, deadjakk commented
> Hi @deadjakk! It works great. I have a couple of comments:
> 
>     * I think we could check if the result of _do_ls_ (file_tuples) is a file to prevent downloading directories.
> 
>     * Could you change they year in the copyright header to 2021?
> 
> 
> Thanks!

Committed these changes!

2021-06-28 18:38 UTC, 0xdeaddood commented
Thanks @deadjakk! Merging.

2021-06-28 18:42 UTC, merged