Support HTTP WWW-Authenticate: Negotiate
SecureAuthCorp/impacket pull request #1146
Opened 2021-08-26 05:11 UTC by LZD-TMoreggia

Servers advertising `WWW-Authenticate: Negotiate` should accept NTLM authentication with a different header. This has been tested against ADCS Web service.

2021-09-01 01:29 UTC, 0xdeaddood requested changes
If the server only has the `Negotiate: Kerberos` provider enabled, we won't receive any NTLM challenge from it. This will produce an error in the function _do_ntlm_negotiate()_ in the _httprelayserver_. To avoid this error, you need to add `return False` after line 86: `LOG.error('No NTLM challenge returned from server')`

2021-09-06 09:49 UTC, LZD-TMoreggia commented
Return value added

2021-09-06 20:45 UTC, 0xdeaddood approved these changes

2021-09-06 20:58 UTC, 0xdeaddood commented
Thanks, @LZD-TMoreggia! Merging...

2021-09-06 20:58 UTC, merged

2021-09-13 21:40 UTC, gladiatx0r commented
I'm a bit confused by this merge. Is the idea that sometimes multiple 'WWW-Authenticate' headers are returned, and one might be 'Negotiate', whereas another 'NTLM'? Or is it that a web server may accept NTLM authentication, even if if there is only one 'WWW-Authenticate' header returned that specifies 'Negotiate'?

If the former, it seems 'getheader' already handles this, as it creates a comma delimited list of all values for any given header. (https://docs.python.org/3/library/http.client.html). If its the later does that assume that Kerberos authentication is disabled, therefore the host falls back to NTLM (https://docs.microsoft.com/en-us/dotnet/framework/wcf/feature-details/understanding-http-authentication)?

2021-09-14 02:02 UTC, 0xdeaddood commented
Hi @gladiatx0r!

> I'm a bit confused by this merge. Is the idea that sometimes multiple 'WWW-Authenticate' headers are returned, and one might be 'Negotiate', whereas another 'NTLM'? Or is it that a web server may accept NTLM authentication, even if if there is only one 'WWW-Authenticate' header returned that specifies 'Negotiate'?

The second option. If the server presents the `WWW-Authenticate: Negotiate` header it would accept NTLM authentication (as long as it have the `Negotiate` provider enabled). If the server only has the `Negotiate: Kerberos` provider enabled, it will refuse the NTLM authentication (we'll never receive the NTLM challenge).