remove duplicate code related to ccache loadfile
SecureAuthCorp/impacket pull request #1166
Opened 2021-09-27 23:22 UTC by rmaksimov

I've added the parseFile function to ccache.py and have refactored all the duplicate code in other scripts

2022-02-09 19:09 UTC, martingalloar requested changes

2022-02-09 19:09 UTC, martingalloar commented on impacket/krb5/ccache.py
> +    def parseFile(cls, domain, username='', target=''):
Maybe we can add some docstrings to make sure it's clear what's expected for each parameter.

2022-02-09 19:09 UTC, martingalloar commented on impacket/tds.py
> +            domain, username, _, TGS = CCache.parseFile(domain, username, 'MSSQLSvc/%s:%d' % (self.server, self.port))
@0xdeaddood pointed out that here obtaining the TGT is required because it will be later on needed.

2022-03-09 18:31 UTC, rmaksimov commented
thanks for the review, i seem to have fixed all the requested things

2022-03-11 15:15 UTC, merged

2022-03-11 15:17 UTC, 0xdeaddood commented
thanks a lot for this PR @rmaksimov!